# Site settings

title: Aditya Wagh
firstname: Aditya
secondname: Wagh

author: Aditya Wagh
logo: /assets/images/icon.png
lang: en-US
resume_link: https://raw.githubusercontent.com/ad1tyawagh/resume/master/aditya_resume.pdf
baseurl: ""
url: "https://www.adityawagh.ml/" 
twitter_username: ad1tyawagh
github_username: ad1tyawagh
linkedin_username: waghaditya
general_email: aditya@adityawagh.ml

# Build settings 

remote_theme: ad1tyawagh/ad1tyawagh.github.io
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  parse_block_html: true
highlighter: rouge  
sass:
  style: compressed

# Other options

permalink: blog/:title

plugins:
- github-pages
- jekyll-seo-tag
- jekyll-menus
- jekyll-remote-theme 
- jekyll-archives
- jekyll-compose 
- jemoji
- jekyll-youtube
- jekyll-seo-tag 
- jekyll-font-awesome-sass
- jekyll-autoprefixer