# Site settings
title: Aditya Wagh
firstname: Aditya
secondname: Wagh
general_email: aditya@adityawagh.ml
author: Aditya Wagh
logo: /assets/images/icon.png
lang: en-US
resume_link: https://raw.githubusercontent.com/adityamwagh/cv/master/AdityaWagh_CV.pdf
baseurl: ""
url: "https://www.adityawagh.ml/"
twitter: adityamwagh
github: adityamwagh
linkedin: adityamwagh
stackoverflow: 11957253/adityamwagh

# Build settings
remote_theme: adityamwagh/adityamwagh.github.io
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    block:
      line_numbers: false
sass:
  style: compressed
# Other options

permalink: blog/:title

plugins:
  - github-pages
  - jekyll-seo-tag
  - jekyll-menus
  - jekyll-remote-theme
  - jekyll-archives
  - jekyll-compose
  - jemoji
  - jekyll-youtube
  - jekyll-seo-tag
  - jekyll-font-awesome-sass
  - jekyll-autoprefixer
